name: CI (CMake Presets)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-latest
          preset: ci-ubuntu
          compiler: gcc
          cxx: g++
          boost-packages: libboost-system-dev libboost-filesystem-dev
        - os: ubuntu-latest
          preset: ci-ubuntu
          compiler: clang
          cxx: clang++
          boost-packages: libboost-system-dev libboost-filesystem-dev

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Cache Boost
      uses: actions/cache@v3
      with:
        path: /var/cache/apt/archives
        key: ${{ runner.os }}-apt-boost-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-apt-boost-

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ${{ matrix.compiler }} ${{ matrix.boost-packages }} ccache

    - name: Set up ccache
      uses: actions/cache@v3
      with:
        path: ~/.ccache
        key: ${{ runner.os }}-ccache-${{ matrix.compiler }}-${{ hashFiles('**/CMakeLists.txt') }}

    - name: Configure CMake
      run: |
        ccache --show-stats
        CC=${{ matrix.compiler }} CXX=${{ matrix.cxx }} cmake --preset ${{ matrix.preset }} -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

    - name: Build
      run: cmake --build --preset ${{ matrix.preset }} --parallel

    - name: Test
      run: ctest --preset ${{ matrix.preset }}
